### ISSUE TITLE
Related Links

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#1]
Hi!
We've noticed that the "related links" metadata is not showing up in the item level record. It still appears when editing an item, but it looks like it is just hidden from the metadata when viewing the item (this applies to all items). 
Thanks in advance for your help!

**Comment by scande3** [comment]
This should be resolved due to the following commit: https://github.com/CollegeOfTheHolyCross/dta/commit/ff6e290fd121cff7fd6b7ff922eefd5ca1647ac7 . Thanks!

**Comment by ntantum** [comment]
Thank you!
