### ISSUE TITLE
Deleting Collections

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#10]
Hello! I haven't been able to figure out how to delete collections since the site was updated. I need to delete a duplicate collection but there is no option in the collection drop-down menu. Let me know if I am just missing it!

**Comment by scande3** [comment]
The functionality still exists but it seems I did forget to create an action for that. Will be added this weekend for use on Monday.

**Comment by scande3** [comment]
@ntantum : This should now be fixed.

**Comment by ntantum** [comment]
Thanks!
