### ISSUE TITLE
"X" Collection

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#11]
We recently added a collection titled "Xpressions and Monarch Publications" but, in the collection listing, the "X" is still grayed out (as if we there are no collections starting with X). The collection can only be seen in the "All" list if you scroll to the bottom. Could this be fixed so that the "x" is a link that shows this collection?

Thanks!

**Comment by scande3** [comment]
That is weird. I'll correct that logic this weekend.

**Comment by scande3** [comment]
@ntantum : This should now be fixed.

**Comment by ntantum** [comment]
Thank you!
