### ISSUE TITLE
Publisher facet on the back end

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#12]
Hey Steven!
When you have a moment, could you turn on the Publisher facet/filter on the back end? Some students have suggested that it would be useful when they process. Thanks!

**Comment by scande3** [comment]
This should now be added when a user is logged in and not visible to others.

**Comment by kjrawson** [comment]
Awesome––thanks!!

**Comment by kjrawson** [comment]
Looks like I closed this too soon! When you do a blank search, then expand the Publisher facet, if you click "more" you get a "Network Error." Thanks!

**Comment by scande3** [comment]
@kjrawson : Hadn't seen this re-opened. Will fix this weekend.

**Comment by scande3** [comment]
@kjrawson : This is now fixed. Thanks!

**Comment by kjrawson** [comment]
Working great now. Thanks!
