### ISSUE TITLE
Linking out to one particular collection

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#13]
Hey, Steven.
This is a minor issue, but it keeps tripping me up. I have been trying to send a link to one of our contributors, the Gay & Lesbian Memory in Action archive (out of South Africa), and I believe the ampersand in the title is making it impossible. 

So, when I do a search like this:
https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Discovery+Resources&f%5Binstitution_name_ssim%5D%5B%5D=Gay+%26+Lesbian+Memory+in+Action+%28GALA%29

it comes up as no results because there is no institution named "Gay." 

Thanks!

**Comment by scande3** [comment]
This link is showing results for me in Chrome. Did something change or is it that it isn't showing the correct number of results? Or is it something I need to test in Safari?

**Comment by kjrawson** [comment]
Try this one: https://www.digitaltransgenderarchive.net/catalog?f%5Bprimary_institution_ssi%5D%5B%5D=Gay+&+Lesbian+Memory+in+Action+(GALA)&per_page=50

**Comment by scande3** [comment]
What does that link generate from on the site?

**Comment by kjrawson** [comment]
I cannot retrace my steps for navigating to that page so I guess we can close this ticket for now! Every other way that I navigate to their materials seems fine.
