### ISSUE TITLE
Viewer Problem

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#16]
Hi Steven!

We are currently uploading a [new photograph collection](https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Kewpie+Photographs&sort=dta_sortable_date_dtsi+asc%2C+title_primary_ssort+asc) that consists of all TIFF files. Our student worker has started to upload them but I noticed that, when clicking on thumbnail, the image viewer pops up but the image does not. At first, I thought it might be the size of the TIFF file but I tested it with a jpeg as well and it still did not come up. 

I quickly looked at another collection that we host, the [Alison Laing Photographs collection](https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Alison+Laing%27s+Photographs&sort=dta_sortable_date_dtsi+asc%2C+title_primary_ssort+asc), and it is having the same issue.

**Comment by scande3** [comment]
@ntantum : Fixed around the time this was filed. Thanks!

**Comment by ntantum** [comment]
Thank you!
