### ISSUE TITLE
Institution Image

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#18]
Hi Steven!

I added a new institution recently ([Grupo Dignidade](https://www.digitaltransgenderarchive.net/inst/xg94hp54d)) but I am having trouble adding an image for the institution.

Every time I try to upload this image:
![grupo dignidade](https://user-images.githubusercontent.com/30127831/42040497-c319bab4-7abd-11e8-86b7-2f26c3ae076e.jpg)

I get this error message:
<img width="1034" alt="screen shot 2018-06-28 at 10 24 53 am" src="https://user-images.githubusercontent.com/30127831/42040511-cdd8071c-7abd-11e8-8aac-7cab3cb6b5d7.png">

I have played around with file types just in case the issue was with the image file itself, but I keep getting the same error message.

**Comment by scande3** [comment]
@ntantum : This issue should now be fixed. Thanks!

**Comment by ntantum** [comment]
Perfect, thanks!
