### ISSUE TITLE
Error Items

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#19]
Hi Steven! 

I am having trouble editing an institution. I was able to edit the photo and the description attached to it, but I am getting the below error message when I try to change the title.

Institution: [James C. Hormel Gay & Lesbian Center](https://www.digitaltransgenderarchive.net/inst/8bf9b146-b323-4e6a-9277-8ceed00da20b) (now LGBTQIA Center)

Error message: 
<img width="1428" alt="screen shot 2018-08-29 at 10 24 35 am" src="https://user-images.githubusercontent.com/30127831/44794353-5415b700-ab76-11e8-9fee-bca926b0893f.png">

**Comment by ntantum** [comment]
Update: I changed the name of this thread because I have been having some trouble with error messages recently so I figured I would put all the issues here!

When I click "edit object" for [vq27zn474](https://www.digitaltransgenderarchive.net/files/vq27zn474)
<img width="1065" alt="screen shot 2018-09-18 at 9 38 02 am" src="https://user-images.githubusercontent.com/30127831/45691671-08c44800-bb27-11e8-90d1-0921a19f7208.png">

When I click "edit object" for [k643b121h](https://www.digitaltransgenderarchive.net/files/k643b121h)
<img width="1085" alt="screen shot 2018-09-18 at 9 53 35 am" src="https://user-images.githubusercontent.com/30127831/45692431-bb48da80-bb28-11e8-82c4-a3af52adf381.png">

When I click "edit object" for [2f75r807r](https://www.digitaltransgenderarchive.net/files/2f75r807r)
<img width="1051" alt="screen shot 2018-09-18 at 9 56 54 am" src="https://user-images.githubusercontent.com/30127831/45692638-46c26b80-bb29-11e8-9d96-f719456350ba.png">
^ For this one, I think the error is because I was testing out using [redacted] in our creator metadata and the site probably didn't like the brackets. We aren't planning on doing this in the future so I just need to take out that piece of metadata!

[ww72bb50p](https://www.digitaltransgenderarchive.net/files/ww72bb50p) should be linked out to, but I get this error message when I try to add a link
<img width="1130" alt="screen shot 2018-09-18 at 9 58 50 am" src="https://user-images.githubusercontent.com/30127831/45692896-dd8f2800-bb29-11e8-8673-7ffe2c99e4b8.png">
I get this error message also for [th83kz366](https://www.digitaltransgenderarchive.net/files/th83kz366) and [k643b1207](https://www.digitaltransgenderarchive.net/files/k643b1207).

When I click "edit object" for [0p096696q](https://www.digitaltransgenderarchive.net/files/0p096696q)
<img width="1056" alt="screen shot 2018-09-18 at 10 45 04 am" src="https://user-images.githubusercontent.com/30127831/45695732-0aded480-bb30-11e8-811e-ac997113d3c0.png">

When  I click "edit object" for [dn39x161v](https://www.digitaltransgenderarchive.net/files/dn39x161v)
<img width="1128" alt="screen shot 2018-09-18 at 10 48 34 am" src="https://user-images.githubusercontent.com/30127831/45695915-6b6e1180-bb30-11e8-8565-f7c0bb3a1225.png">

When  I click "edit object" for [v118rd58t](https://www.digitaltransgenderarchive.net/files/v118rd58t)
<img width="1025" alt="screen shot 2018-09-18 at 10 57 48 am" src="https://user-images.githubusercontent.com/30127831/45696471-b3416880-bb31-11e8-886b-22d52dca4206.png">

When I click "edit object" for [g445cd15v](https://www.digitaltransgenderarchive.net/files/g445cd15v)
<img width="1120" alt="screen shot 2018-09-18 at 11 31 16 am" src="https://user-images.githubusercontent.com/30127831/45698586-601de480-bb36-11e8-805f-54bc9d68ca4c.png">


Thanks!

**Comment by scande3** [comment]
@ntantum -> These issues should be resolved. Thanks!

**Comment by ntantum** [comment]
Thank you, Steven! I will address these errors today or tomorrow and close this thread if everything looks good!

**Comment by ntantum** [comment]
It all looks good! Thanks!
