### ISSUE TITLE
Thumbnail Default Issue

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#22]
Hello!
We are having a bit of an issue with the thumbnails when uploading new items to the site. I can't figure out a specific pattern but, for about 75% of our new items, the thumbnails are defaulting to either the "audio file" thumbnail (that we use when there is no image) or the "file" thumbnail that appears for restricted items.

In case I am not explaining this clearly, here is a screen grab of some of our recent items:
<img width="1041" alt="screen shot 2018-09-12 at 9 09 46 am" src="https://user-images.githubusercontent.com/30127831/45426958-a0c7ba80-b66b-11e8-98fb-66db53289358.png">

All of the above items have thumbnails and none of them are explicit, but they are appearing with these defaults instead.

This is an easy manual fix - it seems like I can go into the backend and simply press "save item" again and the thumbnail appears correctly, but I wanted to let you know before we start some of our  bigger collections!

Nikki

**Comment by scande3** [comment]
The next time this happens, can you leave that item as it is so that I can look at it and link me to it via email? Thanks!

**Comment by scande3** [comment]
I think I have this fixed now and ran a script to fix any items that were missing a thumbnail if you can verify?

**Comment by ntantum** [comment]
All the items that were missing thumbnails now have thumbnails! Thank you!

However, I uploaded a new test item and it still uploaded without a thumbnail in the search results (you can see my test item [here](https://www.digitaltransgenderarchive.net/files/2514nk545))

**Comment by scande3** [comment]
Will rerun the script to fix these issues for items tonight. A fix for this should be deployed over the weekend.

**Comment by ntantum** [comment]
Looks like this issue was resolved. Thanks, Steven!
