### ISSUE TITLE
Contributor field no longer mandatory (to complete after new site is up)

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#23]
Hey, Steven. We have a number of items that we've had to redact in order to post them. Rather than putting in "Unknown" or "[Redacted]" in the Contributor field, we decided it would be better to not force the Contributor element. There's no rush on this, but sometime in October would be good. Thanks!

**Comment by scande3** [comment]
Contributor should no longer be required.

**Comment by kjrawson** [comment]
I tested this in the lab with students today and it still rejected an upload for not having a contributor.

**Comment by scande3** [comment]
I tested this with the redesign and it was working. Let me know if this isn't the case still. If it still doesn't work, can you link me to a record where "contributor" was forced as a value?

**Comment by kjrawson** [comment]
It's still not working. I can't send an example because it simply won't allow you to upload a new item if there isn't a contributor specified so you need to put something in the field in order to save it.

**Comment by scande3** [comment]
@kjrawson - Can you take screenshots of the error it says or of the field with the value? As Contributor doesn't have a red asterisk by it, that just shouldn't be required as only "Creator" is required?

**Comment by kjrawson** [comment]
I was wrongly testing Creator, which we also need as optional. Could you switch that over, too? Thank you!

**Comment by scande3** [comment]
Creator should no longer be required as well.

**Comment by kjrawson** [comment]
Thank you!
