### ISSUE TITLE
Dates in List vs. Gallery View

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#24]
Hi Steven - 

I recently noticed that dates are showing up differently in the List vs. Gallery views for search results.

In the Gallery view, the date is being pulled from Date Issued, which looks good. But in the List view, the date is pulling from Date Published, which often comes up as unknown (our metadata favors Date Issued over Date Published)

Here is an example of this from the same search results: [Gallery view with dates](https://www.digitaltransgenderarchive.net/catalog?q=%22female+husband%22&search_field=all_fields&sort=dta_sortable_date_dtsi+asc%2C+title_primary_ssort+asc&view=gallery) vs. [List view with unknown dates](https://www.digitaltransgenderarchive.net/catalog?q=%22female+husband%22&search_field=all_fields&sort=dta_sortable_date_dtsi+asc%2C+title_primary_ssort+asc&view=list)

Would this be something you could switch around? So that the search results are showing the Date Issued?

**Comment by scande3** [comment]
@ntantum -> This should now be fixed if you can verify? Thanks!

**Comment by ntantum** [comment]
Looks great! Thanks, Steven!
