### ISSUE TITLE
View All Items button

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#25]
Hi Steven! I think I have emailed you about this in the past but I wanted to officially put it up here so I don't forget.

We are still looking to add a "View All Items" option to the collection and institution pages. I have heard from some users of the site that they do not know how to view the whole collection from those pages (they do not realize that a blank search is an option).

I think we had discussed putting it under the institution/collection image so as not to confuse people near the search bar. Let me know if you need more information from us!

**Comment by scande3** [comment]
@ntantum -> This has been added to the Institution and Collection pages. Let me know if it needs adjustment. Thanks!

**Comment by ntantum** [comment]
Looks great! Thank you, Steven!
