### ISSUE TITLE
Minor graphic change to homepage

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#26]
Hey, Steven.
I just noticed that the "How Do I Get Started?" header on the homepage has a question mark in a totally different font than the title itself (when viewing in Chrome). Is that possible to change? Thanks!

**Comment by scande3** [comment]
The "DTA" font lacks a stylized "?" mark and thus defaults to that plain one. I can see the mockup has a stylized image used there so can see if I can fix it in the next day or two.

**Comment by kjrawson** [comment]
Thanks!

**Comment by scande3** [comment]
@kjrawson -> This should be fixed

**Comment by kjrawson** [comment]
Looks great, @scande3. Thanks!!
