### ISSUE TITLE
Recurring error message

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#38]
Hi, Steven.
We've been getting an error message for some time and though it has always been a false error, I thought it was time to tell you about it. I've included a screen grab below. This error happens when saving a new item to the collection, though the item does seem to be saved properly. I can't quite figure out when it happens, but it may be that it occurs when there's a lot of metadata or the file is large and it takes a long time to upload. 
Thanks!

<img width="1272" alt="Screen Shot 2019-09-12 at 8 22 14 PM" src="https://user-images.githubusercontent.com/15388345/64829723-7ae53680-d59b-11e9-8919-b8e21b8e12ee.png">

**Comment by scande3** [comment]
Solution to this was discussed via email.
