### ISSUE TITLE
Harvesting Cornell collection

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#41]
Hey, Steven.
One of our partners, Cornell University, has a collection that we'd like to harvest. Here's the overview: https://digital.library.cornell.edu/collections/impersonator-postcards. 

And here's the full collection: https://digital.library.cornell.edu/?f%5Bcollection_tesim%5D%5B%5D=Postcards+of+female+and+male+impersonators+and+cross-dressing+in+Europe+and+the+United+States%2C+1900-1930&search_field=all_fields&view=gallery

Since there are so many items it seems better to try to harvest it rather than processing them individually. Half of the collection is the back side of the postcards (not sure why they did it that way). However, I can always manually remove the back side items afterwards if that's easier than excluding them from a harvest.
Thanks!

**Comment by scande3** [comment]
Link to JSON version of their collections: https://digital.library.cornell.edu/?f%5Bcollection_tesim%5D%5B%5D=Postcards+of+female+and+male+impersonators+and+cross-dressing+in+Europe+and+the+United+States%2C+1900-1930&page=1&per_page=100&search_field=all_fields&view=gallery&format=json

Need to manually edit the page number to get next matches. Thumbnail in that list. Use ID to get to the object record and request the JSON version.
