### ISSUE TITLE
Institution alphebetical order error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#43]
https://www.digitaltransgenderarchive.net/inst?filter=P%2CQ%2CR%2CS%2CT

When viewing All, The Arquives is in the A’s after Arizona Queer Archives. The Lesbian, Gay, Bisexual, and Transgender Community center is in the L’s after the Leather archive. When breaking the list into the alphabetical pages, both are in the P-T section, but both are at the top of the page before the P’s not in the T’s as you might expect from “the” being in the title.

If they could be listed alphabetically without the "The" considered, that would be ideal. Thanks!

**Comment by scande3** [comment]
This is mostly fixed. Institutions should all be correct... however, for collections, one still shows up under "T". I'm guessing there is some weird character issue there to figure out.

**Comment by kjrawson** [comment]
Okay, thanks! I'll leave this ticket open for a bit, then.
