### ISSUE TITLE
Harvesting of Transvestia

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#44]
If possible, we'd love to harvest this collection:
https://vault.library.uvic.ca/collections/6576cedf-1282-4089-8351-08f73f4199b4

We can do the mapping if there's a workable API and this seems doable!

**Comment by scande3** [comment]
The system is based on Hyrax. Hyrax does have support for machine readable viewing - but this is broken in their implementation. I'm unsure if you can contact them about it? An example from the first record showing that some field is undefined when requesting the page as JSON:
> https://vault.library.uvic.ca/concern/generic_works/47c6e7a5-d411-4cc8-9f4e-1210a9e84302.json

Their "Help" page isn't very helpful for documentation: https://vault.library.uvic.ca/help?locale=en

Harvesting this might be required to parse the HTML of the page which is possible if there isn't a better way to get their data.

**Comment by kjrawson** [comment]
Thanks for this update, Steven. I'll reach out to them now!
