### ISSUE TITLE
Map page copy change [High priority]

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#46]
Hi, Steven.
I am so glad to see that NU has made progress with the server setup and you are working on getting the proper permissions––that’s great! Feel free to back burner the other projects I had asked you about until the transfer happens.

We have had some feedback from users about the map feature being confusing. Could you add the copy below after the light gray “Only items with location data are shown below”?

“Browse the map to view objects related to a particular location. Points on the map show items with content related to that location, not where the item is held or where it was created.” 

Thank you!

Best,
K.J.

**Comment by scande3** [comment]
This should be complete.

**Comment by kjrawson** [comment]
Thank you!
