### ISSUE TITLE
Changed copy for Contact Us Page

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#49]
Hi, Steven!
When you get a chance, could you update the contact us page with the following copy? Everything else is fine on the page, but we're getting more requests for internships that we can handle and we wanted to be clearer about donating. Thanks!

___________________

Thank you for your interest in the Digital Transgender Archive! If you have suggestions or questions about the project, please use this form to contact us.

If you would like to get involved, here are a few options:

Donate Materials
Materials on this site are provided by a range of institutions, from small non-profit organizations to large universities. If your organization is interested in partnering with the DTA to present information on your holdings or to provide access to digital materials, please contact us. 

We also welcome individuals to donate privately owned materials to the project. Please reach out to discuss whether we can include your materials on the site and, if you want to permanently donate your items, we can work with you to find a physical archives that would be a good fit.

Volunteer and Internship Opportunities
If you have brief suggestions for the site, ideas for future projects, or proposals for possible contributors, please feel free to email us at any time. If you a Northeastern University student interested in volunteering on a regular basis or, if you are interested in a more formal internship or co-op, please email us to begin a conversation about joining our team. Unfortunately, we are not able to support volunteers or interns from outside of NU at this time.

Join our Mailing List
Joining our email list is a great way to stay in touch. Our periodic emails will provide project updates, links to news stories, and other important information.

Spread the Word
Spread the word about the DTA through our social media outlets and by linking to our site!

**Comment by scande3** [comment]
This should be complete.

**Comment by kjrawson** [comment]
My apologies, there were two small errors:
–Could you hyphenate "privately-owned" in the second paragraph under "Donate Materials"?
–Could you add "are" to the second sentence under "volunteer and internship opportunities" so that it reads, "If you are a Northeaster University student..."?
Thank you!
