### ISSUE TITLE
Table of contents brackets

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#51]
Hi, Steven.
We are having trouble with the Table of Contents field saving brackets around the input. When we try to remove them and resave, it adds another set of brackets.
Here's an example: https://www.digitaltransgenderarchive.net/files/9880vr198 
Thanks!

**Comment by scande3** [comment]
I've done what I believe should correct this issue. A list of PIDs for items that might need to be fixed (one can search for these IDs): 
["4m90dv511", "xs55mc10b", "fn106x98v", "zs25x855b", "st74cq55j", "ww72bb641", "jq085k13j", "j6731395f", "rf55z7909", "5425k994d", "jh343s53r", "bz60cw50c", "ht24wj62q", "rv042t302", "jd472w684", "2b88qc44n", "4j03cz833", "79407x401", "3t945q94q"]
