### ISSUE TITLE
Homosaurus Duplicate Entry Error Message

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#6]
Hi Steven - A couple days ago, one of our students kept getting the attached error messages. The error message would appear when she pressed "Save Item" and then the item would be deleted (not saved). I wanted to send them your way because, although this isn't a super frequent occurrence, I have seen versions of this error message multiple times since the switch to 2.0  and thought you should be aware of it. Naturally, I asked the students if they entered in two identical Homosaurus terms accidentally, but none of them remembered doing so.

Let me know if you have any suggestions on how to avoid this error!

![screen shot 2018-04-05 at 3 24 17 pm](https://user-images.githubusercontent.com/30127831/38633362-675a666e-3d8d-11e8-9e86-bf0c0aa7eee0.png)
![screen shot 2018-04-05 at 3 36 36 pm](https://user-images.githubusercontent.com/30127831/38633363-676577d4-3d8d-11e8-8317-f0a7517d1c8f.png)

**Comment by scande3** [comment]
@ntantum : This should now be fixed where duplicates do not cause an error (just the duplicate is dropped). Let me know if you still experience or can cause it to occur. Thanks!

**Comment by ntantum** [comment]
Perfect, thanks!
