### ISSUE TITLE
Delete one institution

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#60]
When I try to delete the Lili Elbe Archive institution I get an error: https://www.digitaltransgenderarchive.net/inst/kd17cs89j.

Thanks!

**Comment by scande3** [comment]
It looks like that institution has collections + items. From looking at the details of the collections, it appears they also belong to a different institution as well.

Is it possible to edit each of the collections to remove the Lili Elbe Archive institution? Once that is done, then delete the Lili Elbe Archive institution?

**Comment by kjrawson** [comment]
It worked once I removed it from all of those collections. Thank you!
