### ISSUE TITLE
Accented letter not displaying

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta#69]
For new items, we are able to add accented letters in names and they stick (see [this example](https://www.digitaltransgenderarchive.net/files/5h73pw404)). But, when we try to edit an existing item (such as [this](https://www.digitaltransgenderarchive.net/files/1v53jx05d)) with Yoseñio, it reverts to Yosenio

**Comment by scande3** [comment]
Temporary fix is in place for this that should allow an update.

**Comment by kjrawson** [comment]
Okay if I close this or do you want to leave it open for a more permanent fix?
