### ISSUE TITLE
Batch Edit [high priority]

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#8]
Hi Steven!

Is there a way to bring back the "batch edit" function? I need to change the "genre" for a large number of items and was hoping to avoid doing this one by one.

Thanks!

**Comment by scande3** [comment]
@ntantum -> This will be added in an update this weekend (apologies for the delay on these tickets). Did you end up doing this manually or can you outline more of the use case for when I do local testing?

**Comment by ntantum** [comment]
I did not end up fixing them manually so you can test with this collection! [The Buffalo Belles Newsletters collection](https://www.digitaltransgenderarchive.net/col/gf06g2949) currently has every item listed as both "Newsletter" and "Periodical" for the genre, but I need to edit all 81 items to just be "Newsletter". Let me know if you have any questions! Thanks!

**Comment by scande3** [comment]
@ntantum -> With failover work complete outside of some port issues, am working on this next and apologies for the delay. Should be tested and done in the next few days. Along with this will come better bookmarking support. (The initial enablement was part of the collection update. One can now bookmark items in search results and view them via the drop down menu next to one's logged in name in the black admin bar).

Thanks!

**Comment by ntantum** [comment]
Thanks, Steven!

**Comment by kjrawson** [comment]
Love the bookmark feature, Steven! Seems like a good back-end test case for future front-end use for users who create accounts?

**Comment by ntantum** [comment]
Hi Steven! I don't see the batch edit function on the DTA so I just wanted to check-in with you to see where you are in the process of adding this function. Thanks in advance!

**Comment by scande3** [comment]
@ntantum : I updated those items. The batch edit mode will likely be another week or two.

**Comment by ntantum** [comment]
Thanks for the update!
