### ISSUE TITLE
Deleting Items in a Field

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta#9]
Hi Steven! I have been encountering some issues when trying to delete items from a field.

In [this item](https://www.digitaltransgenderarchive.net/files/f1881k98h), I need to clear the link from the Alternative Title field.

In [this item](https://www.digitaltransgenderarchive.net/files/1g05fb663), I need to clear the link from the publisher field.

No matter how I clear it in the back end, the fields will not clear. This seems to only happen when attempting to leave a field blank after something has already been inputted.

Let me know if you have any further questions!

**Comment by scande3** [comment]
Will be fixed this weekend. Thanks!

**Comment by scande3** [comment]
@ntantum : This should now be fixed.

**Comment by ntantum** [comment]
Thanks, Steven!
